modLoader="javafml" #mandatory
loaderVersion="[28.1]" #mandatory. 26 for 1.14.2, 27 for 1.14.3
credits="Thanks suppergerrie2 for this example!" #optional
[[mods]] #mandatory
modId="tutorialmod" #mandatory
version="1.0" #mandatory
displayName="Tutorial Mod" #mandatory
description='''
A mod developed for suppergerrie2's tutorial, copied by RefundGarbage
'''